name: dust
description: dust
version: 0.0.3
homepage: https://github.com/andcan/dust

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  coverage: ^0.13.9
  lint: ^1.2.0
  mockito: ^4.1.1
  test: ^1.14.5

